[tool.poetry]
name = "search-engine-with-llm-and-agents"
version = "0.1.0"
description = ""
authors = ["Tarun"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
